version: '3'

networks:
    laravel:

services:
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
            args:
                - PHPUSER=${PHPUSER:-www-data}
                - PHPGROUP=${PHPGROUP:-www-data}
        container_name: php
        volumes:
            - ../:/var/www/html:delegated
        networks:
            - laravel

    artisan:
        build:
            context: ./php
            dockerfile: Dockerfile
            args:
                - PHPUSER=${PHPUSER:-www-data}
                - PHPGROUP=${PHPGROUP:-www-data}
        container_name: artisan
        volumes:
            - ../:/var/www/html:delegated
        working_dir: /var/www/html
        entrypoint: [ 'php', '/var/www/html/artisan' ]
        networks:
            - laravel
